name: Call Trivyd
on:
 push:
   branches: [main]
 pull_request:
jobs:
  scan:
    name: Scan
    uses: polymetis-project/actions/.github/workflows/reusable-trivy.yml@main
    with:
      image-name: 'ghcr.io/polymetis-project/wordsmith-web'
      image-tag: gha-${{ github.run_id }}

 
